name: CI FastAPI

on:
  push:
    branches:
      - main
      - migration-python
  pull_request:
    branches:
      - main
      - migration-python

jobs:
  # tests unitaires et d'intégration
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install Python and `uv`
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install `uv`
        run: pip install uv

      - name: Install dependencies
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          source .venv/bin/activate
          pytest tests

  # 2️⃣ Vérification du formatage avec `black`
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install `black`
        run: pip install black

      - name: Check format with black
        run: black --check .

  # Linting avec `ruff`
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install `ruff`
        run: pip install ruff

      - name: Run linting
        run: ruff check --output-format=github --target-version=py39

